### ISSUE TITLE
Validation of the parsed dictionary and construction of final API URL

### ISSUE THREAD

**Issue by Raya679** [neurobagel/query-tool-ai#16]
# Outcome

- The extracted values from the LLM need to be validated against the [Neurobagel Query model](https://github.com/neurobagel/api/blob/main/app/api/models.py)
- Get the appropriate term url for diagnosis, assessment tool, sex  and image modality
- Construct the final api url from the user query

### Validations 
User prompt : How many users with min age 80 and max age 30
Model: ` Sorry but minimum age can’t be bigger than maximum age `

User promt : Healthy consubjects diagnosed with Parkinson's.
Model: `Subjects cannot both be healthy controls and have a diagnosis.`

### Fetching termURLs 
diagnosis : 'schizophrenia'
output : snomed:58214004

assessment : 'zuckerman sensation seeking scale'
output : cogatlas:trm_56abebfe9aaa3

## Tasks
- [x] #17
- [x] #19
- [x] #23

**Comment by rmanaem** [comment]
@Raya679 Feel free to close this milestone since it has been addressed 🎉
